### ISSUE TITLE
investigate docker with canvasAPI

### ISSUE THREAD

**Issue by bellettichloe** [EECE3093C/team-project-red-CanvasAPI#18]
https://github.com/ubccapico/canvas_api_examples/tree/master/api_scripts/python

**Comment by izhall0927** [comment]
I have tried to install and run it 6 separate times and it keeps saying its not supported on this mac

**Comment by izhall0927** [comment]
I may be getting somewhere with it

**Comment by izhall0927** [comment]
Tried a couple of different ways, was successful in implementing Docker but it still didn't solve the issue of canvasAPI still not bein recognized
